use std::fs;
use std::path::{Path, PathBuf};

use ergo_runtime::common::Phase;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleStatus {
    Enforced,
    Deferred,
    /// This rule is satisfied by enforcement of another rule ID.
    Alias {
        enforced_by: &'static str,
    },
}

impl RuleStatus {
    fn as_str(&self) -> String {
        match self {
            RuleStatus::Enforced => "enforced".to_string(),
            RuleStatus::Deferred => "deferred".to_string(),
            RuleStatus::Alias { enforced_by } => format!("alias -> {enforced_by}"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleDefinition {
    pub id: &'static str,
    pub phase: Phase,
    pub summary: &'static str,
    pub predicate: &'static str,
    pub doc_anchor: &'static str,
    pub status: RuleStatus,
}

fn phase_name(phase: Phase) -> &'static str {
    match phase {
        Phase::Registration => "Registration",
        Phase::Composition => "Composition",
        Phase::Execution => "Execution",
    }
}

fn repo_root() -> PathBuf {
    // `crates/ergo-cli` -> `crates` -> repo root
    let here = Path::new(env!("CARGO_MANIFEST_DIR"));
    here.parent()
        .and_then(|p| p.parent())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn registry_output_path() -> PathBuf {
    repo_root().join("docs/STABLE/RULE_REGISTRY.md")
}

pub fn gen_docs_command(args: &[String]) -> Result<String, String> {
    let mut check = false;
    for arg in args {
        match arg.as_str() {
            "--check" => check = true,
            _ => return Err(usage()),
        }
    }

    let out_path = registry_output_path();
    let generated = generate_rule_registry_markdown();

    if check {
        let existing = fs::read_to_string(&out_path)
            .map_err(|err| format!("read {}: {err}", out_path.display()))?;
        if normalize_newlines(&existing) != normalize_newlines(&generated) {
            return Err(format!(
                "generated docs do not match committed file: {}\n(run: ergo gen-docs to update)",
                out_path.display()
            ));
        }
        return Ok("✓ Docs up-to-date\n".to_string());
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    fs::write(&out_path, &generated)
        .map_err(|err| format!("write {}: {err}", out_path.display()))?;

    Ok(format!("✓ Generated {}\n", out_path.display()))
}

fn usage() -> String {
    "usage: ergo gen-docs [--check]".to_string()
}

fn normalize_newlines(s: &str) -> String {
    s.replace("\r\n", "\n")
}

fn generate_rule_registry_markdown() -> String {
    let mut out = String::new();

    out.push_str("---\n");
    out.push_str("Authority: STABLE\n");
    out.push_str("Version: v0\n");
    out.push_str("Generated: true\n");
    out.push_str("---\n\n");
    out.push_str("# Rule Registry (Generated)\n\n");
    out.push_str("This file is generated by `ergo gen-docs` from the code-side rule registry.\n");
    out.push_str("Do not edit by hand.\n\n");

    render_group(
        &mut out,
        "Adapter (ADP-*)",
        ADAPTER_RULES,
        "STABLE/PRIMITIVE_MANIFESTS/adapter.md",
    );
    render_group(
        &mut out,
        "Source (SRC-*)",
        SOURCE_RULES,
        "STABLE/PRIMITIVE_MANIFESTS/source.md",
    );
    render_group(
        &mut out,
        "Compute (CMP-*)",
        COMPUTE_RULES,
        "STABLE/PRIMITIVE_MANIFESTS/compute.md",
    );
    render_group(
        &mut out,
        "Trigger (TRG-*)",
        TRIGGER_RULES,
        "STABLE/PRIMITIVE_MANIFESTS/trigger.md",
    );
    render_group(
        &mut out,
        "Action (ACT-*)",
        ACTION_RULES,
        "STABLE/PRIMITIVE_MANIFESTS/action.md",
    );
    render_group(
        &mut out,
        "Composition (COMP-*)",
        COMPOSITION_RULES,
        "STABLE/PRIMITIVE_MANIFESTS (distributed)",
    );
    render_group(
        &mut out,
        "Cluster (D./I./E./V.)",
        CLUSTER_RULES,
        "STABLE/CLUSTER_SPEC.md",
    );

    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn render_group(out: &mut String, title: &str, rules: &[RuleDefinition], primary_doc: &str) {
    out.push_str(&format!("## {title}\n\n"));
    out.push_str(&format!("Primary spec: `{primary_doc}`\n\n"));
    out.push_str("| Rule ID | Phase | Status | Summary | Predicate | Docs |\n");
    out.push_str("|---------|-------|--------|---------|-----------|------|\n");

    for rule in rules {
        let predicate = format!("`{}`", rule.predicate);
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | `{}` |\n",
            rule.id,
            phase_name(rule.phase),
            rule.status.as_str(),
            rule.summary,
            predicate,
            rule.doc_anchor
        ));
    }

    out.push('\n');
}

// ---- Rule sets (mirror of STABLE docs) ---------------------------------

const ADAPTER_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "ADP-1",
        phase: Phase::Registration,
        summary: "ID format valid",
        predicate: "regex(id, /^[a-z][a-z0-9_]*$/)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-2",
        phase: Phase::Registration,
        summary: "Version valid semver",
        predicate: "semver.valid(version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-3",
        phase: Phase::Registration,
        summary: "Runtime compatibility satisfied",
        predicate: "runtime.version >= runtime_compatibility",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-4",
        phase: Phase::Registration,
        summary: "Provides something",
        predicate: "context_keys.len > 0 OR event_kinds.len > 0",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-5",
        phase: Phase::Registration,
        summary: "Context key names unique",
        predicate: "unique(context_keys[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-6",
        phase: Phase::Registration,
        summary: "Context key types valid",
        predicate: "all(context_keys[].type in {Number, Bool, String, Series})",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-7",
        phase: Phase::Registration,
        summary: "Event kind names unique",
        predicate: "unique(event_kinds[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-7",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-8",
        phase: Phase::Registration,
        summary: "Event schemas valid JSON Schema",
        predicate: "json_schema.validate(payload_schema, draft: 2020-12)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-9",
        phase: Phase::Registration,
        summary: "Capture format version present",
        predicate: "capture.format_version != \"\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-10",
        phase: Phase::Registration,
        summary: "Capture fields referentially valid",
        predicate: "all(capture.fields[] in CaptureFieldSet(adapter))",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-10",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-11",
        phase: Phase::Registration,
        summary: "Writable flag must be present",
        predicate: "all(context_keys[].writable is present)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-12",
        phase: Phase::Registration,
        summary: "Effect names unique",
        predicate: "unique(accepts.effects[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-12",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-13",
        phase: Phase::Registration,
        summary: "Effect schemas valid",
        predicate: "all(accepts.effects[].payload_schema is valid Draft 2020-12)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-14",
        phase: Phase::Registration,
        summary: "Writable implies set_context accepted",
        predicate: "any(writable == true) => accepts contains \"set_context\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-14",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-15",
        phase: Phase::Registration,
        summary: "Writable keys must be capturable (planned)",
        predicate: "all(writable == true => \"context.\" + name in capture.fields)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-15",
        status: RuleStatus::Deferred,
    },
    RuleDefinition {
        id: "ADP-16",
        phase: Phase::Registration,
        summary: "Write effect must be capturable (planned)",
        predicate: "any(writable == true) => \"effect.set_context\" in capture.fields",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-16",
        status: RuleStatus::Deferred,
    },
    RuleDefinition {
        id: "ADP-17",
        phase: Phase::Registration,
        summary: "Writable keys cannot be required",
        predicate: "all(writable == true => required == false)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-17",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-18",
        phase: Phase::Registration,
        summary: "Required event fields map to context keys with compatible types",
        predicate: "all(required(event.payload_schema) fields exist in context_keys with matching ValueType)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-18",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ADP-19",
        phase: Phase::Registration,
        summary: "Materialized event field types are supported",
        predicate: "event payload object fields map only to Number/Bool/String/Series",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#ADP-19",
        status: RuleStatus::Enforced,
    },
];

const SOURCE_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "SRC-1",
        phase: Phase::Registration,
        summary: "ID format valid",
        predicate: "regex(id, /^[a-z][a-z0-9_]*$/)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-2",
        phase: Phase::Registration,
        summary: "Version valid semver",
        predicate: "semver.valid(version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-3",
        phase: Phase::Registration,
        summary: "Kind is \"source\"",
        predicate: "kind == \"source\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-4",
        phase: Phase::Registration,
        summary: "No inputs declared",
        predicate: "inputs.len == 0",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-5",
        phase: Phase::Registration,
        summary: "At least one output",
        predicate: "outputs.len >= 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-6",
        phase: Phase::Registration,
        summary: "Output names unique",
        predicate: "unique(outputs[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-7",
        phase: Phase::Registration,
        summary: "Output types valid",
        predicate: "all(outputs[].type ∈ ValueType)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-7",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-8",
        phase: Phase::Registration,
        summary: "State not allowed",
        predicate: "state.allowed == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-9",
        phase: Phase::Registration,
        summary: "Side effects not allowed",
        predicate: "side_effects == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-12",
        phase: Phase::Registration,
        summary: "Execution deterministic",
        predicate: "execution.deterministic == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-12",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-13",
        phase: Phase::Registration,
        summary: "Cadence is continuous",
        predicate: "execution.cadence == continuous",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-14",
        phase: Phase::Registration,
        summary: "ID unique in registry",
        predicate: "!registry.contains_key(id)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-14",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-15",
        phase: Phase::Registration,
        summary: "Parameter default type matches declared type",
        predicate:
            "parameters[].default == None || typeof(parameters[].default) == parameters[].type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-15",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-16",
        phase: Phase::Registration,
        summary: "$key context references bound to declared parameter",
        predicate: "∀ ctx where name starts with \"$\": referenced param exists",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-16",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-17",
        phase: Phase::Registration,
        summary: "$key context references must be String type",
        predicate: "∀ ctx where name starts with \"$\": referenced param.type == String",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-17",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "SRC-10",
        phase: Phase::Composition,
        summary: "Required context keys exist in adapter",
        predicate: "source.requires.context.filter(required).keys ⊆ adapter.provides.context.keys",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-10",
        status: RuleStatus::Alias {
            enforced_by: "COMP-1",
        },
    },
    RuleDefinition {
        id: "SRC-11",
        phase: Phase::Composition,
        summary: "Required context types match adapter",
        predicate:
            "∀ k where required: source.requires.context[k].ty == adapter.provides.context[k].ty",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/source.md#SRC-11",
        status: RuleStatus::Alias {
            enforced_by: "COMP-2",
        },
    },
];

const COMPUTE_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "CMP-1",
        phase: Phase::Registration,
        summary: "ID format valid",
        predicate: "regex(id, /^[a-z][a-z0-9_]*$/)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-2",
        phase: Phase::Registration,
        summary: "Version valid semver",
        predicate: "semver.valid(version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-3",
        phase: Phase::Registration,
        summary: "Kind is \"compute\"",
        predicate: "kind == \"compute\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-4",
        phase: Phase::Registration,
        summary: "At least one input",
        predicate: "inputs.len >= 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-5",
        phase: Phase::Registration,
        summary: "Input names unique",
        predicate: "unique(inputs[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-6",
        phase: Phase::Registration,
        summary: "At least one output",
        predicate: "outputs.len >= 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-7",
        phase: Phase::Registration,
        summary: "Output names unique",
        predicate: "unique(outputs[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-7",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-8",
        phase: Phase::Registration,
        summary: "Side effects not allowed",
        predicate: "side_effects == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-9",
        phase: Phase::Registration,
        summary: "State resettable if allowed",
        predicate: "state.allowed => state.resettable",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-10",
        phase: Phase::Registration,
        summary: "Errors deterministic",
        predicate: "errors.allowed => errors.deterministic",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-10",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-11",
        phase: Phase::Execution,
        summary: "All outputs produced on success",
        predicate: "compute() -> Ok(outputs) includes every declared output",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-12",
        phase: Phase::Execution,
        summary: "No outputs produced on error",
        predicate: "compute() -> Err(_) emits no outputs",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-12",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-13",
        phase: Phase::Registration,
        summary: "Input types valid",
        predicate: "inputs[].type ∈ {Number, Bool, Series}",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-14",
        phase: Phase::Registration,
        summary: "Input cardinality single",
        predicate: "inputs[].cardinality == single",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-14",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-15",
        phase: Phase::Registration,
        summary: "Parameter types valid",
        predicate: "parameters[].type ∈ {Int, Number, Bool}",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-15",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-16",
        phase: Phase::Registration,
        summary: "Cadence is continuous",
        predicate: "execution.cadence == continuous",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-16",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-17",
        phase: Phase::Registration,
        summary: "Execution deterministic",
        predicate: "execution.deterministic == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-17",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-18",
        phase: Phase::Registration,
        summary: "ID unique in registry",
        predicate: "!registry.contains_key(id)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-18",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-19",
        phase: Phase::Registration,
        summary: "Parameter default type matches declared type",
        predicate:
            "parameters[].default == None || typeof(parameters[].default) == parameters[].type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-19",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "CMP-20",
        phase: Phase::Registration,
        summary: "Output types valid",
        predicate: "all(outputs[].type ∈ ValueType)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#CMP-20",
        status: RuleStatus::Enforced,
    },
];

const TRIGGER_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "TRG-1",
        phase: Phase::Registration,
        summary: "ID format valid",
        predicate: "regex(id, /^[a-z][a-z0-9_]*$/)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-2",
        phase: Phase::Registration,
        summary: "Version valid semver",
        predicate: "semver.valid(version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-3",
        phase: Phase::Registration,
        summary: "Kind is \"trigger\"",
        predicate: "kind == \"trigger\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-4",
        phase: Phase::Registration,
        summary: "At least one input",
        predicate: "inputs.len >= 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-5",
        phase: Phase::Registration,
        summary: "Input names unique",
        predicate: "unique(inputs[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-6",
        phase: Phase::Registration,
        summary: "Input types valid",
        predicate: "all(inputs[].type ∈ TriggerValueType)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-7",
        phase: Phase::Registration,
        summary: "Exactly one output",
        predicate: "outputs.len == 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-7",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-8",
        phase: Phase::Registration,
        summary: "Output is event type",
        predicate: "outputs[0].type == \"event\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-9",
        phase: Phase::Registration,
        summary: "State not allowed",
        predicate: "state.allowed == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-10",
        phase: Phase::Registration,
        summary: "Side effects not allowed",
        predicate: "side_effects == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-10",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-11",
        phase: Phase::Registration,
        summary: "Execution deterministic",
        predicate: "execution.deterministic == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-12",
        phase: Phase::Registration,
        summary: "Input cardinality single",
        predicate: "inputs[].cardinality == single",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-12",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-13",
        phase: Phase::Registration,
        summary: "ID unique in registry",
        predicate: "!registry.contains_key(id)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "TRG-14",
        phase: Phase::Registration,
        summary: "Parameter default type matches declared type",
        predicate:
            "parameters[].default == None || typeof(parameters[].default) == parameters[].type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#TRG-14",
        status: RuleStatus::Enforced,
    },
];

const ACTION_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "ACT-1",
        phase: Phase::Registration,
        summary: "ID format valid",
        predicate: "regex(id, /^[a-z][a-z0-9_]*$/)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-2",
        phase: Phase::Registration,
        summary: "Version valid semver",
        predicate: "semver.valid(version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-3",
        phase: Phase::Registration,
        summary: "Kind is \"action\"",
        predicate: "kind == \"action\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-4",
        phase: Phase::Registration,
        summary: "At least one event input",
        predicate: "any(inputs[].type == \"event\")",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-5",
        phase: Phase::Registration,
        summary: "Input names unique",
        predicate: "unique(inputs[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-6",
        phase: Phase::Registration,
        summary: "Input types valid",
        predicate: "all(inputs[].type ∈ ActionValueType)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-7",
        phase: Phase::Registration,
        summary: "Exactly one output",
        predicate: "outputs.len == 1",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-7",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-8",
        phase: Phase::Registration,
        summary: "Output named \"outcome\"",
        predicate: "outputs[0].name == \"outcome\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-9",
        phase: Phase::Registration,
        summary: "Output is event type",
        predicate: "outputs[0].type == \"event\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-10",
        phase: Phase::Registration,
        summary: "State not allowed",
        predicate: "state.allowed == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-10",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-11",
        phase: Phase::Registration,
        summary: "Side effects required",
        predicate: "side_effects == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-12",
        phase: Phase::Composition,
        summary: "Gated by trigger",
        predicate: "(validation phase, R.7)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-12",
        status: RuleStatus::Alias { enforced_by: "V.5" },
    },
    RuleDefinition {
        id: "ACT-13",
        phase: Phase::Registration,
        summary: "Effects block present",
        predicate: "effects is present",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-14",
        phase: Phase::Registration,
        summary: "Write names unique",
        predicate: "unique(effects.writes[].name)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-14",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-15",
        phase: Phase::Registration,
        summary: "Write types valid",
        predicate: "all(effects.writes[].type ∈ {Number, Bool, String})",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-15",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-16",
        phase: Phase::Registration,
        summary: "Retryable false",
        predicate: "execution.retryable == false",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-16",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-17",
        phase: Phase::Registration,
        summary: "Execution deterministic",
        predicate: "execution.deterministic == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-17",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-18",
        phase: Phase::Registration,
        summary: "ID unique in registry",
        predicate: "!registry.contains_key(id)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-18",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-19",
        phase: Phase::Registration,
        summary: "Parameter default type matches declared type",
        predicate:
            "parameters[].default == None || typeof(parameters[].default) == parameters[].type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-19",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-20",
        phase: Phase::Registration,
        summary: "$key write references bound to declared parameter",
        predicate: "∀ write where name starts with \"$\": referenced param exists",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-20",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-21",
        phase: Phase::Registration,
        summary: "$key write references must be String type",
        predicate: "∀ write where name starts with \"$\": referenced param.type == String",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-21",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-22",
        phase: Phase::Registration,
        summary: "Write from_input references declared input",
        predicate: "∀ write: from_input ∈ inputs[].name",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-22",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "ACT-23",
        phase: Phase::Registration,
        summary: "Write from_input type compatible with write type",
        predicate: "∀ write: inputs[from_input].type is scalar AND matches write.value_type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#ACT-23",
        status: RuleStatus::Enforced,
    },
];

const COMPOSITION_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "COMP-1",
        phase: Phase::Composition,
        summary: "Source context requirements satisfied",
        predicate: "source.requires.context.filter(required).keys ⊆ adapter.provides.context.keys",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#COMP-1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-2",
        phase: Phase::Composition,
        summary: "Source context types match",
        predicate: "∀ k where required: source.requires.context[k].ty == adapter.provides.context[k].ty",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#COMP-2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-3",
        phase: Phase::Composition,
        summary: "Capture format version supported",
        predicate: "runtime.supports_capture(adapter.capture.format_version)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/adapter.md#COMP-3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-4",
        phase: Phase::Composition,
        summary: "Source output type equals Compute input type",
        predicate: "source.output.type == compute.input.type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#COMP-4",
        status: RuleStatus::Alias { enforced_by: "V.4" },
    },
    RuleDefinition {
        id: "COMP-5",
        phase: Phase::Composition,
        summary: "Input type equals upstream output type",
        predicate: "upstream.output.type == compute.input.type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#COMP-5",
        status: RuleStatus::Alias { enforced_by: "V.4" },
    },
    RuleDefinition {
        id: "COMP-6",
        phase: Phase::Composition,
        summary: "Output type equals downstream input type",
        predicate: "compute.output.type == downstream.input.type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/compute.md#COMP-6",
        status: RuleStatus::Alias { enforced_by: "V.4" },
    },
    RuleDefinition {
        id: "COMP-7",
        phase: Phase::Composition,
        summary: "Trigger input from Compute or Trigger",
        predicate: "upstream.kind ∈ {\"compute\", \"trigger\"}",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#COMP-7",
        status: RuleStatus::Alias { enforced_by: "V.2" },
    },
    RuleDefinition {
        id: "COMP-8",
        phase: Phase::Composition,
        summary: "Trigger output to Action or Trigger",
        predicate: "downstream.kind ∈ {\"action\", \"trigger\"}",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/trigger.md#COMP-8",
        status: RuleStatus::Alias { enforced_by: "V.2" },
    },
    RuleDefinition {
        id: "COMP-9",
        phase: Phase::Composition,
        summary: "Action inputs follow gate/payload split",
        predicate: "∀ action input i: (i.type == event => upstream(i).kind == \"trigger\") ∧ (i.type != event => upstream(i).kind ∈ {\"source\",\"compute\"})",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-9",
        status: RuleStatus::Alias { enforced_by: "V.2" },
    },
    RuleDefinition {
        id: "COMP-10",
        phase: Phase::Composition,
        summary: "Action output not wireable",
        predicate: "downstream.len == 0",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-10",
        status: RuleStatus::Alias { enforced_by: "V.2" },
    },
    RuleDefinition {
        id: "COMP-11",
        phase: Phase::Composition,
        summary: "Action writes target provided keys",
        predicate: "effects.writes.names ⊆ adapter.context_keys.names",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-12",
        phase: Phase::Composition,
        summary: "Action writes only writable keys",
        predicate: "∀n ∈ writes: adapter.key[n].writable == true",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-12",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-13",
        phase: Phase::Composition,
        summary: "Action write types match",
        predicate: "∀n ∈ writes: action.type[n] == adapter.key[n].type",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-13",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-14",
        phase: Phase::Composition,
        summary: "If action writes, adapter accepts set_context",
        predicate: "writes.len > 0 => accepts.effects contains \"set_context\"",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-14",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "COMP-15",
        phase: Phase::Composition,
        summary: "Writes captured (planned)",
        predicate:
            "writes.len > 0 => (\"effect.set_context\" ∈ capture.fields AND ∀n: \"context.\" + n ∈ capture.fields)",
        doc_anchor: "STABLE/PRIMITIVE_MANIFESTS/action.md#COMP-15",
        status: RuleStatus::Deferred,
    },
    RuleDefinition {
        id: "COMP-16",
        phase: Phase::Composition,
        summary: "Parameter-bound manifest names resolve",
        predicate: "$-prefixed names resolve to String parameter values",
        doc_anchor: "CANONICAL/PHASE_INVARIANTS.md#COMP-16",
        status: RuleStatus::Enforced,
    },
];

const CLUSTER_RULES: &[RuleDefinition] = &[
    RuleDefinition {
        id: "D.1",
        phase: Phase::Composition,
        summary: "Cluster contains >= 1 node",
        predicate: "cluster.nodes.len >= 1",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.2",
        phase: Phase::Composition,
        summary: "Edges reference existing nodes/ports",
        predicate: "edge endpoints refer to existing nodes/ports",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.3",
        phase: Phase::Composition,
        summary: "Edges satisfy wiring matrix",
        predicate: "wiring_allowed(from.kind, to.kind)",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.3",
        status: RuleStatus::Alias { enforced_by: "V.2" },
    },
    RuleDefinition {
        id: "D.4",
        phase: Phase::Composition,
        summary: "Output ports reference valid internal node outputs",
        predicate: "output_ports[].maps_to refer to existing node outputs",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.5",
        phase: Phase::Composition,
        summary: "Input port names unique",
        predicate: "unique(input_ports[].name)",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.6",
        phase: Phase::Composition,
        summary: "Output port names unique",
        predicate: "unique(output_ports[].name)",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.6",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.8",
        phase: Phase::Composition,
        summary: "Parameter defaults type-compatible",
        predicate: "parameter.default matches parameter.ty",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.8",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.9",
        phase: Phase::Composition,
        summary: "No duplicate parameter names",
        predicate: "unique(parameters[].name)",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.9",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.10",
        phase: Phase::Composition,
        summary: "Declared signature compatible with inferred",
        predicate: "declared_signature <= inferred_signature",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.10",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "D.11",
        phase: Phase::Composition,
        summary: "Declared wireability <= inferred",
        predicate: "declared.wireable <= inferred.wireable",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#D.11",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "E.3",
        phase: Phase::Composition,
        summary: "ExternalInput not an edge sink",
        predicate: "no ExpandedEndpoint::ExternalInput in expanded.edges",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#E.3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.1",
        phase: Phase::Composition,
        summary: "No cycles in graph",
        predicate: "topological_sort succeeds",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.1",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.2",
        phase: Phase::Composition,
        summary: "Edges satisfy wiring matrix (including Action gate/payload input refinement)",
        predicate: "wiring_allowed(from.kind, to.kind) OR (to.kind == action AND to.input.type ∈ {number,bool,string} AND from.kind ∈ {source,compute})",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.2",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.3",
        phase: Phase::Composition,
        summary: "Required inputs connected",
        predicate: "all required inputs have inbound edge",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.3",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.4",
        phase: Phase::Composition,
        summary: "Type constraints satisfied at edges",
        predicate: "edge output type == input expected type",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.4",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.5",
        phase: Phase::Composition,
        summary: "Actions gated by triggers",
        predicate: "every action has inbound trigger event edge",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.5",
        status: RuleStatus::Enforced,
    },
    RuleDefinition {
        id: "V.7",
        phase: Phase::Composition,
        summary: "Each input has <= 1 inbound edge",
        predicate: "inbound_edges(input) <= 1",
        doc_anchor: "STABLE/CLUSTER_SPEC.md#V.7",
        status: RuleStatus::Enforced,
    },
];
